import { COLOR_SCHEME_VARIABLE_ACCENT_COLOR, COLOR_SCHEME_VARIABLE_ACCENT_COLOR_RGB, COLOR_SCHEME_VARIABLE_ACCENT_FOREGROUND_COLOR, COLOR_SCHEME_VARIABLE_ACCENT_FOREGROUND_COLOR_RGB, COLOR_SCHEME_VARIABLE_BACKGROUND_COLOR, COLOR_SCHEME_VARIABLE_BACKGROUND_COLOR_RGB, COLOR_SCHEME_VARIABLE_COLOR_SCHEME, COLOR_SCHEME_VARIABLE_FOREGROUND_COLOR, COLOR_SCHEME_VARIABLE_FOREGROUND_COLOR_RGB, RENDER_COLOR_SCHEME_VARIABLE_PREFIX } from "../COLOR_SCHEME_VARIABLE.mjs";

export const STYLE_SHEET_MANAGER_TYPE_VARIABLES = Object.freeze({
    "accent-color": `${RENDER_COLOR_SCHEME_VARIABLE_PREFIX}${COLOR_SCHEME_VARIABLE_ACCENT_COLOR}`,
    "accent-color-rgb": `${RENDER_COLOR_SCHEME_VARIABLE_PREFIX}${COLOR_SCHEME_VARIABLE_ACCENT_COLOR_RGB}`,
    "accent-foreground-color": `${RENDER_COLOR_SCHEME_VARIABLE_PREFIX}${COLOR_SCHEME_VARIABLE_ACCENT_FOREGROUND_COLOR}`,
    "accent-foreground-color-rgb": `${RENDER_COLOR_SCHEME_VARIABLE_PREFIX}${COLOR_SCHEME_VARIABLE_ACCENT_FOREGROUND_COLOR_RGB}`,
    "background-color": `${RENDER_COLOR_SCHEME_VARIABLE_PREFIX}${COLOR_SCHEME_VARIABLE_BACKGROUND_COLOR}`,
    "background-color-rgb": `${RENDER_COLOR_SCHEME_VARIABLE_PREFIX}${COLOR_SCHEME_VARIABLE_BACKGROUND_COLOR_RGB}`,
    "color-scheme": `${RENDER_COLOR_SCHEME_VARIABLE_PREFIX}${COLOR_SCHEME_VARIABLE_COLOR_SCHEME}`,
    "foreground-color": `${RENDER_COLOR_SCHEME_VARIABLE_PREFIX}${COLOR_SCHEME_VARIABLE_FOREGROUND_COLOR}`,
    "foreground-color-rgb": `${RENDER_COLOR_SCHEME_VARIABLE_PREFIX}${COLOR_SCHEME_VARIABLE_FOREGROUND_COLOR_RGB}`
});
