export const COLOR_SCHEME_VARIABLE_PREFIX = "--flux-color-scheme-";

export const COLOR_SCHEME_VARIABLE_RGB_SUFFIX = "-rgb";

export const COLOR_SCHEME_VARIABLE_ACCENT_COLOR = "accent-color";

export const COLOR_SCHEME_VARIABLE_ACCENT_COLOR_FOREGROUND_COLOR = `${COLOR_SCHEME_VARIABLE_ACCENT_COLOR}-foreground-color`;

export const COLOR_SCHEME_VARIABLE_ACCENT_COLOR_FOREGROUND_COLOR_RGB = `${COLOR_SCHEME_VARIABLE_ACCENT_COLOR_FOREGROUND_COLOR}${COLOR_SCHEME_VARIABLE_RGB_SUFFIX}`;

export const COLOR_SCHEME_VARIABLE_ACCENT_COLOR_RGB = `${COLOR_SCHEME_VARIABLE_ACCENT_COLOR}${COLOR_SCHEME_VARIABLE_RGB_SUFFIX}`;

export const COLOR_SCHEME_VARIABLE_BACKGROUND_COLOR = "background-color";

export const COLOR_SCHEME_VARIABLE_BACKGROUND_COLOR_RGB = `${COLOR_SCHEME_VARIABLE_BACKGROUND_COLOR}${COLOR_SCHEME_VARIABLE_RGB_SUFFIX}`;

export const COLOR_SCHEME_VARIABLE_COLOR_SCHEME = "color-scheme";

export const COLOR_SCHEME_VARIABLE_FOREGROUND_COLOR = "foreground-color";

export const COLOR_SCHEME_VARIABLE_FOREGROUND_COLOR_RGB = `${COLOR_SCHEME_VARIABLE_FOREGROUND_COLOR}${COLOR_SCHEME_VARIABLE_RGB_SUFFIX}`;

export const DEFAULT_COLOR_SCHEME_VARIABLES = Object.freeze([
    COLOR_SCHEME_VARIABLE_ACCENT_COLOR_FOREGROUND_COLOR_RGB,
    COLOR_SCHEME_VARIABLE_ACCENT_COLOR_RGB,
    COLOR_SCHEME_VARIABLE_BACKGROUND_COLOR_RGB,
    COLOR_SCHEME_VARIABLE_COLOR_SCHEME,
    COLOR_SCHEME_VARIABLE_FOREGROUND_COLOR_RGB
]);
