export const COLOR_SCHEME_VARIABLE_ACCENT = "accent";

export const COLOR_SCHEME_VARIABLE_ACCENT_RGB = `${COLOR_SCHEME_VARIABLE_ACCENT}-rgb`;

export const COLOR_SCHEME_VARIABLE_ACCENT_FOREGROUND = `${COLOR_SCHEME_VARIABLE_ACCENT}-foreground`;

export const COLOR_SCHEME_VARIABLE_ACCENT_FOREGROUND_RGB = `${COLOR_SCHEME_VARIABLE_ACCENT_FOREGROUND}-rgb`;

export const COLOR_SCHEME_VARIABLE_BACKGROUND = "background";

export const COLOR_SCHEME_VARIABLE_BACKGROUND_RGB = `${COLOR_SCHEME_VARIABLE_BACKGROUND}-rgb`;

export const COLOR_SCHEME_VARIABLE_FOREGROUND = "foreground";

export const COLOR_SCHEME_VARIABLE_FOREGROUND_RGB = `${COLOR_SCHEME_VARIABLE_FOREGROUND}-rgb`;
