import { LOCALIZATION_KEY_DARK, LOCALIZATION_KEY_LIGHT, LOCALIZATION_KEY_SYSTEM, LOCALIZATION_KEY_SYSTEM_WITH_COLOR_SCHEME } from "./LOCALIZATION_KEY.mjs";

export const TEXTS_DE_CH = Object.freeze({
    [LOCALIZATION_KEY_DARK]: "Dunkel",
    [LOCALIZATION_KEY_LIGHT]: "Hell",
    [LOCALIZATION_KEY_SYSTEM]: "System",
    [LOCALIZATION_KEY_SYSTEM_WITH_COLOR_SCHEME]: "System ({color-scheme})"
});
