import { LOCALIZATION_KEY_DARK, LOCALIZATION_KEY_LIGHT, LOCALIZATION_KEY_SYSTEM_BASED } from "./LOCALIZATION_KEY.mjs";

export const TEXTS_EN = Object.freeze({
    [LOCALIZATION_KEY_DARK]: "Dark",
    [LOCALIZATION_KEY_LIGHT]: "Light",
    [LOCALIZATION_KEY_SYSTEM_BASED]: "System based"
});
